version: '3.4'

services:
  mysql:
    image: mysql:8
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "S3cret"
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_USER: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./tmp/mysql:/var/lib/mysql
