version: '3.4'

x-healthcheck-defaults: &default-healthchecks
  interval: 30s
  timeout: 10s
  retries: 3

x-woot-volumes: &woot-volumes
  - ./:/usr/app
  - /usr/app/node_modules

services:
  postgres:
    image: postgres:14-alpine
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
